<a href="https://colab.research.google.com/github/khemsu/ML_from_Scratch/blob/main/BasicAboutNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [50]:
# a = np.array([1,2,3], dtype= 'int32')
# print(a)

[1 2 3]


In [51]:
# a.dtype

dtype('int32')

gives in bytes

In [52]:
# a.itemsize

4

In [19]:
# a.ndim


1

In [20]:
# a.shape

(3,)

In [18]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [21]:
b.ndim

2

In [22]:
b.shape


(2, 3)

In [44]:
c = np.array([[[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18]]])
print(c)

[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]
  [13 14 15 16 17 18]]]


In [45]:
c.ndim

3

first value is (blocks, rows in obe block, columns in one block)
note: since three values are given that means 3 dimensional array.

In [53]:
c.shape

(1, 3, 6)

In [47]:
c.reshape(2,3,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [48]:
c.dtype

dtype('int64')

Accessing/Changing specific elements , rows, columns, etc

In [55]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [56]:
#getting specific element
a[1,5]

13

In [58]:
#Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [61]:
#Get a specific column(last column)
a[:,6]

array([ 7, 14])

In [63]:
#changing the specific element
a[0,5] = 10
print(a)

[[ 1  2  3  4  5 10  7]
 [ 8  9 10 11 12 13 14]]


In [66]:
# getting specific range of elements
# [startindex:endindex:stepsize]
a[0, 1:10:1]

array([ 2,  3,  4,  5, 10,  7])

Generating Random arrays

In [67]:
var = np.random.rand(3,3)
print(var)

[[0.71121745 0.29598421 0.53846922]
 [0.71602832 0.34027962 0.27626472]
 [0.62023122 0.29765558 0.54312328]]


In [70]:
var1 = np.random.seed(3)
print(var)

[[0.71121745 0.29598421 0.53846922]
 [0.71602832 0.34027962 0.27626472]
 [0.62023122 0.29765558 0.54312328]]


random.seed(42) set the

In [83]:
#for random integer
# (start,end, size=(3,3))
np.random.seed(42)  # Set the seed, and helps generate same random number everytime
var2= np.random.randint(4,7, size=(3,3))
print(var2)

[[6 4 6]
 [6 4 4]
 [6 5 6]]


In [85]:
np.random.seed(42)
print(var2)


[[6 4 6]
 [6 4 4]
 [6 5 6]]
